<a href="https://colab.research.google.com/github/kingspy89/ml_learnings-/blob/main/pipline_learning_on_titanic/predict_without_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle
import numpy as np


In [21]:
ohe_sex= pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl','rb'))
clf = pickle.load(open('clf.pkl','rb'))

In [4]:

test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [14]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1)).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [15]:
test_input_sex

array([[0., 1.]])

In [16]:

test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1)).toarray()

In [17]:
test_input_embarked


array([[0., 0., 1.]])

In [18]:
test_input_age = test_input[:,2].reshape(1,1)

In [19]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)


In [23]:
clf.predict(test_input_transformed)

array([0])